apiVersion: v1
kind: Namespace
metadata:
  name: vinicius-carvalho

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinicius-teste
  namespace: vinicius-carvalho
  labels:
    app: vinicius
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vinicius
  replicas: 1
  template:
    metadata:
      labels:
        app: vinicius
    spec:
      containers:
        - image: vinicpires/vinicius-jackexperts:final
          name: nginx-vinicius

---
apiVersion: v1
kind: Service
metadata:
  name: desafio-vinicius-carvalho
  namespace: vinicius-carvalho
spec:
  selector:
    app: vinicius
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vinicius
  namespace: vinicius-carvalho

spec:
  ingressClassName: nginx
  rules:
    - host: vinicius-carvalho.stag.jac.bsb.br
      http:
        paths:
          - backend:
              service:
                name: desafio-vinicius-carvalho
                port:
                  number: 80
            path: /
            pathType: Prefix
